# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d127559a99d0f507db42ab6d621e08a00a158b2b4de41733008d6d5ccbd3e0201881bfa6e7ca85faf252443689b8214b8cf38e1593ab94e1382766c69c2cd970

test:
  secret_key_base: 4d711fe953d340bf909af4660af3285ff762f8d852e151b0d706682b4867419628d2442ccd5b660652ea0e3260d3f566d4fb5d8ee5847633fd22347bbac0c271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
